// Auto-generated Audio Map with Alice Voice ID
export const AUDIO_MAP = {
  "Oliver is designing a running track with two curved semicircle ends and a rectangle middle. How can we find the total distance around without losing track?": "/assets/audio/wonder_hook.mp3",
  "How can Oliver and Maya design a track with curved ends without guessing the distance? Oliver and Maya are setting up a running track for Grade 6 sports day. The middle section is a rectangle, but both ends are capped with semicircles. How can they calculate the exact boundary length?": "/assets/audio/story_1_combined.mp3",
  "Oliver and Maya are setting up a running track for Grade 6 sports day. The middle section is a rectangle, but both ends are capped with semicircles. How can they calculate the exact boundary length?": "/assets/audio/story_1_pure.mp3",
  "How can Oliver and Maya design a track with curved ends without guessing the distance?": "/assets/audio/story_1_q.mp3",
  "In math, a composite figure is a shape made by combining two or more basic shapes!": "/assets/audio/story_1_f.mp3",
  "What is the relationship between the radius and the diameter of a circle? Before tackling composite figures, Orbit reminds us of key circle facts: the radius 'r' goes from center to edge, while the diameter 'd' spans all the way across through the center point. Remember: d = 2r!": "/assets/audio/story_2_combined.mp3",
  "Before tackling composite figures, Orbit reminds us of key circle facts: the radius 'r' goes from center to edge, while the diameter 'd' spans all the way across through the center point. Remember: d = 2r!": "/assets/audio/story_2_pure.mp3",
  "What is the relationship between the radius and the diameter of a circle?": "/assets/audio/story_2_q.mp3",
  "The radius is always half of the diameter (r = d ÷ 2).": "/assets/audio/story_2_f.mp3",
  "What happens when you combine two identical semicircles together? Look closely at the running track ends! Semicircle 1 on the left and Semicircle 2 on the right are identical. When joined together, they form ONE full complete circle!": "/assets/audio/story_3_combined.mp3",
  "Look closely at the running track ends! Semicircle 1 on the left and Semicircle 2 on the right are identical. When joined together, they form ONE full complete circle!": "/assets/audio/story_3_pure.mp3",
  "What happens when you combine two identical semicircles together?": "/assets/audio/story_3_q.mp3",
  "Two halves make a whole! Joining 2 semicircles gives 1 full circle.": "/assets/audio/story_3_f.mp3",
  "How do we calculate the distance around a circle? The total distance around any circle is called its Circumference (C). Formula: C = π × d or C = 2 × π × r. We use π ≈ 3.14 or π ≈ 22/7 depending on the given numbers!": "/assets/audio/story_4_combined.mp3",
  "The total distance around any circle is called its Circumference (C). Formula: C = π × d or C = 2 × π × r. We use π ≈ 3.14 or π ≈ 22/7 depending on the given numbers!": "/assets/audio/story_4_pure.mp3",
  "How do we calculate the distance around a circle?": "/assets/audio/story_4_q.mp3",
  "Circumference is just the math word for a circle's perimeter.": "/assets/audio/story_4_f.mp3",
  "How do we find the area inside a circle compared to a rectangle? The area of the middle rectangle is simply length × width. The area of a full circle is π × r². For a semicircle, divide by 2! For a quarter circle, divide by 4!": "/assets/audio/story_5_combined.mp3",
  "The area of the middle rectangle is simply length × width. The area of a full circle is π × r². For a semicircle, divide by 2! For a quarter circle, divide by 4!": "/assets/audio/story_5_pure.mp3",
  "How do we find the area inside a circle compared to a rectangle?": "/assets/audio/story_5_q.mp3",
  "Rectangle Area = L × W. Circle Area = π × r².": "/assets/audio/story_5_f.mp3",
  "How do we find the total area of the running track? To find the total area of a composite figure formed by joining shapes, simply calculate each part's area separately and add them together! Total Area = Rectangle Area + Circle Area.": "/assets/audio/story_6_combined.mp3",
  "To find the total area of a composite figure formed by joining shapes, simply calculate each part's area separately and add them together! Total Area = Rectangle Area + Circle Area.": "/assets/audio/story_6_pure.mp3",
  "How do we find the total area of the running track?": "/assets/audio/story_6_q.mp3",
  "Composite Area = Add the individual shape areas together!": "/assets/audio/story_6_f.mp3",
  "What is the key rule when finding the perimeter of a composite figure? Warning! When calculating the total perimeter around the outer boundary, ONLY add outer straight edges and outer curved arcs. NEVER double count internal joining edges!": "/assets/audio/story_7_combined.mp3",
  "Warning! When calculating the total perimeter around the outer boundary, ONLY add outer straight edges and outer curved arcs. NEVER double count internal joining edges!": "/assets/audio/story_7_pure.mp3",
  "What is the key rule when finding the perimeter of a composite figure?": "/assets/audio/story_7_q.mp3",
  "Perimeter TRAP: Internal edges where shapes attach are excluded!": "/assets/audio/story_7_f.mp3",
  "What are the three steps to master any composite figure? Oliver, Maya, and Orbit are ready for victory! Master composite figures in 3 simple steps: 1. Split the figure into basic shapes. 2. Solve each part. 3. Combine by adding or subtracting!": "/assets/audio/story_8_combined.mp3",
  "Oliver, Maya, and Orbit are ready for victory! Master composite figures in 3 simple steps: 1. Split the figure into basic shapes. 2. Solve each part. 3. Combine by adding or subtracting!": "/assets/audio/story_8_pure.mp3",
  "What are the three steps to master any composite figure?": "/assets/audio/story_8_q.mp3",
  "Split, Solve, Combine — you're ready for Simulate!": "/assets/audio/story_8_f.mp3",
  "Welcome to Shape Splitter Table! Drag or tap shapes to assemble the target composite figure matching labelled dimensions.": "/assets/audio/sim_station1.mp3",
  "Welcome to Circle Slicer Bench! Slice the circle into halves and quarters to observe area and perimeter fractions.": "/assets/audio/sim_station2.mp3",
  "Welcome to Perimeter Path Tracer! Trace the outer perimeter step by step. Remember to skip internal joining edges!": "/assets/audio/sim_station3.mp3",
  "Practice — Choose Your World! Answer questions in each world. Earn stars and XP!": "/assets/audio/world_select_header.mp3",
  "World 1: Round Table Yard. Master radius, diameter, and full circle circumference!": "/assets/audio/world_intro_1.mp3",
  "World 2: Garden Path Grove. Calculate the area of full circles with ease!": "/assets/audio/world_intro_2.mp3",
  "World 3: Wheel Works. Discover perimeter and area of semicircles!": "/assets/audio/world_intro_3.mp3",
  "World 4: Pizza Palace. Explore quarter circles and slice through perimeters and areas!": "/assets/audio/world_intro_4.mp3",
  "World 5: Window Wonderland. Solve composite areas formed by adding shape plus circle part!": "/assets/audio/world_intro_5.mp3",
  "World 6: Coin Cove. Master composite area subtraction — removing circular cutouts!": "/assets/audio/world_intro_6.mp3",
  "World 7: Running Track Raceway. Calculate total composite perimeters without double counting inside edges!": "/assets/audio/world_intro_7.mp3",
  "World 8: Clock Tower City. Learn when to use pi as 3.14 or 22 over 7 for fast computation!": "/assets/audio/world_intro_8.mp3",
  "World 9: Word Problem Woods. Solve multi-step real world story problems with circles!": "/assets/audio/world_intro_9.mp3",
  "World 10: Challenge Colosseum. Conquer mixed multi-shape composite figures in the ultimate arena!": "/assets/audio/world_intro_10.mp3",
  "Sam measured a circular clock face with a radius of 8 cm. What is its diameter?": "/assets/audio/w1_q1_prompt.mp3",
  "Remember that diameter = 2 × radius.": "/assets/audio/w1_q10_hint_raw.mp3",
  "Hint: Remember that diameter = 2 × radius.": "/assets/audio/w1_q10_hint_prefixed.mp3",
  "Leo is wrapping a ribbon around a circular rug with radius 10 m. (Use π = 3.14). What is the circumference?": "/assets/audio/w1_q2_prompt.mp3",
  "Use the formula C = 2 × π × r.": "/assets/audio/w1_q7_hint_raw.mp3",
  "Hint: Use the formula C = 2 × π × r.": "/assets/audio/w1_q7_hint_prefixed.mp3",
  "Emma is wrapping a ribbon around a circular rug with radius 21 m. (Use π = 22/7). What is the circumference?": "/assets/audio/w1_q3_prompt.mp3",
  "Sophia is wrapping a ribbon around a circular rug with radius 28 m. (Use π = 22/7). What is the circumference?": "/assets/audio/w1_q4_prompt.mp3",
  "Emma has a round tabletop with a diameter of 36 cm. What is its radius?": "/assets/audio/w1_q5_prompt.mp3",
  "Remember that radius = diameter ÷ 2.": "/assets/audio/w1_q9_hint_raw.mp3",
  "Hint: Remember that radius = diameter ÷ 2.": "/assets/audio/w1_q9_hint_prefixed.mp3",
  "Chloe measured a circular clock face with a radius of 11 cm. What is its diameter?": "/assets/audio/w1_q6_prompt.mp3",
  "Liam is wrapping a ribbon around a circular rug with radius 7 m. (Use π = 22/7). What is the circumference?": "/assets/audio/w1_q7_prompt.mp3",
  "Sam measured a circular clock face with a radius of 9 cm. What is its diameter?": "/assets/audio/w1_q8_prompt.mp3",
  "Sam has a round tabletop with a diameter of 46 cm. What is its radius?": "/assets/audio/w1_q9_prompt.mp3",
  "Sam measured a circular clock face with a radius of 22 cm. What is its diameter?": "/assets/audio/w1_q10_prompt.mp3",
  "Liam is painting a circular target with a radius of 21 cm. (Use π = 22/7). What is the area of the circle?": "/assets/audio/w2_q1_prompt.mp3",
  "Area formula is A = π × r × r.": "/assets/audio/w2_q1_hint_raw.mp3",
  "Hint: Area formula is A = π × r × r.": "/assets/audio/w2_q1_hint_prefixed.mp3",
  "Emma is painting a circular target with a radius of 7 cm. (Use π = 22/7). What is the area of the circle?": "/assets/audio/w2_q2_prompt.mp3",
  "Chloe is painting a circular target with a radius of 21 cm. (Use π = 22/7). What is the area of the circle?": "/assets/audio/w2_q3_prompt.mp3",
  "Leo is painting a circular target with a radius of 7 cm. (Use π = 22/7). What is the area of the circle?": "/assets/audio/w2_q4_prompt.mp3",
  "Ethan is painting a circular target with a radius of 4 cm. (Use π = 3.14). What is the area of the circle?": "/assets/audio/w2_q5_prompt.mp3",
  "Ethan is painting a circular target with a radius of 5 cm. (Use π = 3.14). What is the area of the circle?": "/assets/audio/w2_q6_prompt.mp3",
  "Oliver is painting a circular target with a radius of 5 cm. (Use π = 3.14). What is the area of the circle?": "/assets/audio/w2_q7_prompt.mp3",
  "Ethan is painting a circular target with a radius of 7 cm. (Use π = 22/7). What is the area of the circle?": "/assets/audio/w2_q8_prompt.mp3",
  "Chloe is painting a circular target with a radius of 12 cm. (Use π = 3.14). What is the area of the circle?": "/assets/audio/w2_q9_prompt.mp3",
  "Liam is painting a circular target with a radius of 7 cm. (Use π = 22/7). What is the area of the circle?": "/assets/audio/w2_q10_prompt.mp3",
  "Leo cut a circular watermelon in half. If the radius is 12 cm, what is the area of one semicircle slice? (Use π = 3.14)": "/assets/audio/w3_q1_prompt.mp3",
  "Semicircle area is half of the full circle area!": "/assets/audio/w3_q10_hint_raw.mp3",
  "Hint: Semicircle area is half of the full circle area!": "/assets/audio/w3_q10_hint_prefixed.mp3",
  "Leo built a semicircular garden bed with radius 6 m. What is the total perimeter around the garden (arc + straight base)? (Use π = 3.14)": "/assets/audio/w3_q2_prompt.mp3",
  "Don't forget to add the straight diameter edge to the curved arc!": "/assets/audio/w3_q8_hint_raw.mp3",
  "Hint: Don't forget to add the straight diameter edge to the curved arc!": "/assets/audio/w3_q8_hint_prefixed.mp3",
  "Sophia cut a circular watermelon in half. If the radius is 6 cm, what is the area of one semicircle slice? (Use π = 3.14)": "/assets/audio/w3_q3_prompt.mp3",
  "Maya cut a circular watermelon in half. If the radius is 10 cm, what is the area of one semicircle slice? (Use π = 3.14)": "/assets/audio/w3_q4_prompt.mp3",
  "Ethan built a semicircular garden bed with radius 12 m. What is the total perimeter around the garden (arc + straight base)? (Use π = 3.14)": "/assets/audio/w3_q5_prompt.mp3",
  "Emma built a semicircular garden bed with radius 6 m. What is the total perimeter around the garden (arc + straight base)? (Use π = 3.14)": "/assets/audio/w3_q6_prompt.mp3",
  "Ethan cut a circular watermelon in half. If the radius is 6 cm, what is the area of one semicircle slice? (Use π = 3.14)": "/assets/audio/w3_q7_prompt.mp3",
  "Emma built a semicircular garden bed with radius 12 m. What is the total perimeter around the garden (arc + straight base)? (Use π = 3.14)": "/assets/audio/w3_q8_prompt.mp3",
  "Liam cut a circular watermelon in half. If the radius is 12 cm, what is the area of one semicircle slice? (Use π = 3.14)": "/assets/audio/w3_q9_prompt.mp3",
  "Liam cut a circular watermelon in half. If the radius is 10 cm, what is the area of one semicircle slice? (Use π = 3.14)": "/assets/audio/w3_q10_prompt.mp3",
  "Maya ate 1 quarter slice of a round pizza with radius 10 cm. What is the area of that quarter slice? (Use π = 3.14)": "/assets/audio/w4_q1_prompt.mp3",
  "Divide full circle area by 4.": "/assets/audio/w4_q10_hint_raw.mp3",
  "Hint: Divide full circle area by 4.": "/assets/audio/w4_q10_hint_prefixed.mp3",
  "Sophia outlined a quarter-circle fan with radius 8 cm. What is its perimeter (curved arc + 2 straight radii)? (Use π = 3.14)": "/assets/audio/w4_q2_prompt.mp3",
  "Perimeter = curved arc + radius + radius.": "/assets/audio/w4_q8_hint_raw.mp3",
  "Hint: Perimeter = curved arc + radius + radius.": "/assets/audio/w4_q8_hint_prefixed.mp3",
  "Oliver outlined a quarter-circle fan with radius 8 cm. What is its perimeter (curved arc + 2 straight radii)? (Use π = 3.14)": "/assets/audio/w4_q3_prompt.mp3",
  "Leo ate 1 quarter slice of a round pizza with radius 4 cm. What is the area of that quarter slice? (Use π = 3.14)": "/assets/audio/w4_q4_prompt.mp3",
  "Lucas outlined a quarter-circle fan with radius 4 cm. What is its perimeter (curved arc + 2 straight radii)? (Use π = 3.14)": "/assets/audio/w4_q5_prompt.mp3",
  "Maya ate 1 quarter slice of a round pizza with radius 4 cm. What is the area of that quarter slice? (Use π = 3.14)": "/assets/audio/w4_q6_prompt.mp3",
  "Liam ate 1 quarter slice of a round pizza with radius 4 cm. What is the area of that quarter slice? (Use π = 3.14)": "/assets/audio/w4_q7_prompt.mp3",
  "Sam outlined a quarter-circle fan with radius 10 cm. What is its perimeter (curved arc + 2 straight radii)? (Use π = 3.14)": "/assets/audio/w4_q8_prompt.mp3",
  "Sam ate 1 quarter slice of a round pizza with radius 10 cm. What is the area of that quarter slice? (Use π = 3.14)": "/assets/audio/w4_q9_prompt.mp3",
  "Sam ate 1 quarter slice of a round pizza with radius 8 cm. What is the area of that quarter slice? (Use π = 3.14)": "/assets/audio/w4_q10_prompt.mp3",
  "Sophia designed a stage shaped like a rectangle (14 m by 14 m) with a semicircle attached to one side (radius = 7 m). What is the total area? (Use π = 22/7)": "/assets/audio/w5_q1_prompt.mp3",
  "Split the figure into a rectangle and a semicircle, then add their areas!": "/assets/audio/w5_q10_hint_raw.mp3",
  "Hint: Split the figure into a rectangle and a semicircle, then add their areas!": "/assets/audio/w5_q10_hint_prefixed.mp3",
  "Sophia designed a stage shaped like a rectangle (10 m by 21 m) with a semicircle attached to one side (radius = 10.5 m). What is the total area? (Use π = 22/7)": "/assets/audio/w5_q2_prompt.mp3",
  "Liam designed a stage shaped like a rectangle (10 m by 14 m) with a semicircle attached to one side (radius = 7 m). What is the total area? (Use π = 22/7)": "/assets/audio/w5_q3_prompt.mp3",
  "Emma designed a stage shaped like a rectangle (20 m by 21 m) with a semicircle attached to one side (radius = 10.5 m). What is the total area? (Use π = 22/7)": "/assets/audio/w5_q4_prompt.mp3",
  "Lucas designed a stage shaped like a rectangle (10 m by 14 m) with a semicircle attached to one side (radius = 7 m). What is the total area? (Use π = 22/7)": "/assets/audio/w5_q5_prompt.mp3",
  "Chloe designed a stage shaped like a rectangle (20 m by 21 m) with a semicircle attached to one side (radius = 10.5 m). What is the total area? (Use π = 22/7)": "/assets/audio/w5_q6_prompt.mp3",
  "Chloe designed a stage shaped like a rectangle (10 m by 7 m) with a semicircle attached to one side (radius = 3.5 m). What is the total area? (Use π = 22/7)": "/assets/audio/w5_q7_prompt.mp3",
  "Chloe designed a stage shaped like a rectangle (14 m by 14 m) with a semicircle attached to one side (radius = 7 m). What is the total area? (Use π = 22/7)": "/assets/audio/w5_q8_prompt.mp3",
  "Emma designed a stage shaped like a rectangle (20 m by 7 m) with a semicircle attached to one side (radius = 3.5 m). What is the total area? (Use π = 22/7)": "/assets/audio/w5_q9_prompt.mp3",
  "Emma designed a stage shaped like a rectangle (14 m by 14 m) with a semicircle attached to one side (radius = 7 m). What is the total area? (Use π = 22/7)": "/assets/audio/w5_q10_prompt.mp3",
  "Sophia cut a circular coin cutout of radius 10 cm out of a square metal plate (20 cm by 20 cm). What is the remaining area? (Use π = 22/7)": "/assets/audio/w6_q1_prompt.mp3",
  "Subtract the area of the circle from the total square area!": "/assets/audio/w6_q10_hint_raw.mp3",
  "Hint: Subtract the area of the circle from the total square area!": "/assets/audio/w6_q10_hint_prefixed.mp3",
  "Ethan cut a circular coin cutout of radius 14 cm out of a square metal plate (28 cm by 28 cm). What is the remaining area? (Use π = 22/7)": "/assets/audio/w6_q2_prompt.mp3",
  "Oliver cut a circular coin cutout of radius 14 cm out of a square metal plate (28 cm by 28 cm). What is the remaining area? (Use π = 22/7)": "/assets/audio/w6_q3_prompt.mp3",
  "Lucas cut a circular coin cutout of radius 7 cm out of a square metal plate (14 cm by 14 cm). What is the remaining area? (Use π = 22/7)": "/assets/audio/w6_q4_prompt.mp3",
  "Leo cut a circular coin cutout of radius 14 cm out of a square metal plate (28 cm by 28 cm). What is the remaining area? (Use π = 22/7)": "/assets/audio/w6_q5_prompt.mp3",
  "Oliver cut a circular coin cutout of radius 10 cm out of a square metal plate (20 cm by 20 cm). What is the remaining area? (Use π = 22/7)": "/assets/audio/w6_q6_prompt.mp3",
  "Liam cut a circular coin cutout of radius 14 cm out of a square metal plate (28 cm by 28 cm). What is the remaining area? (Use π = 22/7)": "/assets/audio/w6_q7_prompt.mp3",
  "Chloe cut a circular coin cutout of radius 7 cm out of a square metal plate (14 cm by 14 cm). What is the remaining area? (Use π = 22/7)": "/assets/audio/w6_q8_prompt.mp3",
  "Oliver cut a circular coin cutout of radius 7 cm out of a square metal plate (14 cm by 14 cm). What is the remaining area? (Use π = 22/7)": "/assets/audio/w6_q9_prompt.mp3",
  "Leo cut a circular coin cutout of radius 7 cm out of a square metal plate (14 cm by 14 cm). What is the remaining area? (Use π = 22/7)": "/assets/audio/w6_q10_prompt.mp3",
  "Chloe is running around a track shaped like a rectangle with two semicircular ends. The straight sides are 40 m long and the semicircles have radius 21 m. What is the outer perimeter? (Use π = 22/7)": "/assets/audio/w7_q1_prompt.mp3",
  "Only sum outer straight sides and outer curves. Never count internal joining lines!": "/assets/audio/w7_q10_hint_raw.mp3",
  "Hint: Only sum outer straight sides and outer curves. Never count internal joining lines!": "/assets/audio/w7_q10_hint_prefixed.mp3",
  "Sophia is running around a track shaped like a rectangle with two semicircular ends. The straight sides are 30 m long and the semicircles have radius 14 m. What is the outer perimeter? (Use π = 22/7)": "/assets/audio/w7_q2_prompt.mp3",
  "Lucas is running around a track shaped like a rectangle with two semicircular ends. The straight sides are 50 m long and the semicircles have radius 7 m. What is the outer perimeter? (Use π = 22/7)": "/assets/audio/w7_q3_prompt.mp3",
  "Oliver is running around a track shaped like a rectangle with two semicircular ends. The straight sides are 50 m long and the semicircles have radius 7 m. What is the outer perimeter? (Use π = 22/7)": "/assets/audio/w7_q4_prompt.mp3",
  "Lucas is running around a track shaped like a rectangle with two semicircular ends. The straight sides are 30 m long and the semicircles have radius 21 m. What is the outer perimeter? (Use π = 22/7)": "/assets/audio/w7_q5_prompt.mp3",
  "Emma is running around a track shaped like a rectangle with two semicircular ends. The straight sides are 40 m long and the semicircles have radius 21 m. What is the outer perimeter? (Use π = 22/7)": "/assets/audio/w7_q6_prompt.mp3",
  "Sam is running around a track shaped like a rectangle with two semicircular ends. The straight sides are 50 m long and the semicircles have radius 14 m. What is the outer perimeter? (Use π = 22/7)": "/assets/audio/w7_q7_prompt.mp3",
  "Sophia is running around a track shaped like a rectangle with two semicircular ends. The straight sides are 40 m long and the semicircles have radius 14 m. What is the outer perimeter? (Use π = 22/7)": "/assets/audio/w7_q8_prompt.mp3",
  "Maya is running around a track shaped like a rectangle with two semicircular ends. The straight sides are 40 m long and the semicircles have radius 14 m. What is the outer perimeter? (Use π = 22/7)": "/assets/audio/w7_q9_prompt.mp3",
  "Sam is running around a track shaped like a rectangle with two semicircular ends. The straight sides are 30 m long and the semicircles have radius 14 m. What is the outer perimeter? (Use π = 22/7)": "/assets/audio/w7_q10_prompt.mp3",
  "Maya is painting a circular target with a radius of 21 cm. (Use π = 22/7). What is the area of the circle?": "/assets/audio/w8_q1_prompt.mp3",
  "Emma needs to calculate the circumference of a circular clock tower dial with radius 14 cm. Which value of π is most efficient for mental calculation?": "/assets/audio/w8_q2_prompt.mp3",
  "Check if 14 can be divided cleanly by 7.": "/assets/audio/w8_q6_hint_raw.mp3",
  "Hint: Check if 14 can be divided cleanly by 7.": "/assets/audio/w8_q6_hint_prefixed.mp3",
  "Emma needs to calculate the circumference of a circular clock tower dial with radius 28 cm. Which value of π is most efficient for mental calculation?": "/assets/audio/w8_q3_prompt.mp3",
  "Check if 28 can be divided cleanly by 7.": "/assets/audio/w8_q3_hint_raw.mp3",
  "Hint: Check if 28 can be divided cleanly by 7.": "/assets/audio/w8_q3_hint_prefixed.mp3",
  "Sophia is wrapping a ribbon around a circular rug with radius 14 m. (Use π = 22/7). What is the circumference?": "/assets/audio/w8_q4_prompt.mp3",
  "Emma is wrapping a ribbon around a circular rug with radius 28 m. (Use π = 22/7). What is the circumference?": "/assets/audio/w8_q5_prompt.mp3",
  "Sophia needs to calculate the circumference of a circular clock tower dial with radius 14 cm. Which value of π is most efficient for mental calculation?": "/assets/audio/w8_q6_prompt.mp3",
  "Lucas is wrapping a ribbon around a circular rug with radius 14 m. (Use π = 22/7). What is the circumference?": "/assets/audio/w8_q7_prompt.mp3",
  "Ethan needs to calculate the circumference of a circular clock tower dial with radius 35 cm. Which value of π is most efficient for mental calculation?": "/assets/audio/w8_q8_prompt.mp3",
  "Check if 35 can be divided cleanly by 7.": "/assets/audio/w8_q8_hint_raw.mp3",
  "Hint: Check if 35 can be divided cleanly by 7.": "/assets/audio/w8_q8_hint_prefixed.mp3",
  "Ethan is painting a circular target with a radius of 21 cm. (Use π = 22/7). What is the area of the circle?": "/assets/audio/w8_q9_prompt.mp3",
  "Oliver is wrapping a ribbon around a circular rug with radius 14 m. (Use π = 22/7). What is the circumference?": "/assets/audio/w8_q10_prompt.mp3",
  "Sam is putting artificial turf on a sports field shaped like a central rectangle (40 m × 28 m) plus two semicircular goal areas at the ends (radius = 14 m). How many square meters of turf are needed in total? (Use π = 22/7)": "/assets/audio/w9_q1_prompt.mp3",
  "Step 1: Find rectangle area. Step 2: Combine the two semicircles into 1 circle area. Step 3: Add them together!": "/assets/audio/w10_q10_hint_raw.mp3",
  "Hint: Step 1: Find rectangle area. Step 2: Combine the two semicircles into 1 circle area. Step 3: Add them together!": "/assets/audio/w10_q10_hint_prefixed.mp3",
  "Liam is putting artificial turf on a sports field shaped like a central rectangle (30 m × 14 m) plus two semicircular goal areas at the ends (radius = 7 m). How many square meters of turf are needed in total? (Use π = 22/7)": "/assets/audio/w9_q2_prompt.mp3",
  "Oliver is putting artificial turf on a sports field shaped like a central rectangle (30 m × 14 m) plus two semicircular goal areas at the ends (radius = 7 m). How many square meters of turf are needed in total? (Use π = 22/7)": "/assets/audio/w9_q3_prompt.mp3",
  "Maya is putting artificial turf on a sports field shaped like a central rectangle (30 m × 14 m) plus two semicircular goal areas at the ends (radius = 7 m). How many square meters of turf are needed in total? (Use π = 22/7)": "/assets/audio/w9_q4_prompt.mp3",
  "Ethan is putting artificial turf on a sports field shaped like a central rectangle (30 m × 28 m) plus two semicircular goal areas at the ends (radius = 14 m). How many square meters of turf are needed in total? (Use π = 22/7)": "/assets/audio/w10_q8_prompt.mp3",
  "Sophia is putting artificial turf on a sports field shaped like a central rectangle (40 m × 14 m) plus two semicircular goal areas at the ends (radius = 7 m). How many square meters of turf are needed in total? (Use π = 22/7)": "/assets/audio/w9_q6_prompt.mp3",
  "Lucas is putting artificial turf on a sports field shaped like a central rectangle (30 m × 14 m) plus two semicircular goal areas at the ends (radius = 7 m). How many square meters of turf are needed in total? (Use π = 22/7)": "/assets/audio/w9_q7_prompt.mp3",
  "Maya is putting artificial turf on a sports field shaped like a central rectangle (20 m × 28 m) plus two semicircular goal areas at the ends (radius = 14 m). How many square meters of turf are needed in total? (Use π = 22/7)": "/assets/audio/w9_q8_prompt.mp3",
  "Lucas is putting artificial turf on a sports field shaped like a central rectangle (20 m × 28 m) plus two semicircular goal areas at the ends (radius = 14 m). How many square meters of turf are needed in total? (Use π = 22/7)": "/assets/audio/w9_q9_prompt.mp3",
  "Maya is putting artificial turf on a sports field shaped like a central rectangle (30 m × 28 m) plus two semicircular goal areas at the ends (radius = 14 m). How many square meters of turf are needed in total? (Use π = 22/7)": "/assets/audio/w9_q10_prompt.mp3",
  "Leo is putting artificial turf on a sports field shaped like a central rectangle (30 m × 14 m) plus two semicircular goal areas at the ends (radius = 7 m). How many square meters of turf are needed in total? (Use π = 22/7)": "/assets/audio/w10_q1_prompt.mp3",
  "Sam is putting artificial turf on a sports field shaped like a central rectangle (20 m × 14 m) plus two semicircular goal areas at the ends (radius = 7 m). How many square meters of turf are needed in total? (Use π = 22/7)": "/assets/audio/w10_q2_prompt.mp3",
  "Leo is putting artificial turf on a sports field shaped like a central rectangle (40 m × 14 m) plus two semicircular goal areas at the ends (radius = 7 m). How many square meters of turf are needed in total? (Use π = 22/7)": "/assets/audio/w10_q3_prompt.mp3",
  "Chloe is putting artificial turf on a sports field shaped like a central rectangle (20 m × 28 m) plus two semicircular goal areas at the ends (radius = 14 m). How many square meters of turf are needed in total? (Use π = 22/7)": "/assets/audio/w10_q4_prompt.mp3",
  "Sophia is putting artificial turf on a sports field shaped like a central rectangle (20 m × 14 m) plus two semicircular goal areas at the ends (radius = 7 m). How many square meters of turf are needed in total? (Use π = 22/7)": "/assets/audio/w10_q5_prompt.mp3",
  "Lucas is putting artificial turf on a sports field shaped like a central rectangle (30 m × 28 m) plus two semicircular goal areas at the ends (radius = 14 m). How many square meters of turf are needed in total? (Use π = 22/7)": "/assets/audio/w10_q6_prompt.mp3",
  "Ethan is putting artificial turf on a sports field shaped like a central rectangle (20 m × 28 m) plus two semicircular goal areas at the ends (radius = 14 m). How many square meters of turf are needed in total? (Use π = 22/7)": "/assets/audio/w10_q7_prompt.mp3",
  "Maya is putting artificial turf on a sports field shaped like a central rectangle (40 m × 14 m) plus two semicircular goal areas at the ends (radius = 7 m). How many square meters of turf are needed in total? (Use π = 22/7)": "/assets/audio/w10_q9_prompt.mp3",
  "Emma is putting artificial turf on a sports field shaped like a central rectangle (40 m × 28 m) plus two semicircular goal areas at the ends (radius = 14 m). How many square meters of turf are needed in total? (Use π = 22/7)": "/assets/audio/w10_q10_prompt.mp3",
  "What did you learn about composite figures with circles? Explain it to Maya with an example!": "/assets/audio/reflect_prompt.mp3"
};
